import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { cn } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "bg-[#EFEFEF] flex flex-col min-h-screen")}>
                <Analytics />
                {children}
            </body>
        </html>
    );
}
